---
sidebar: sidebar 
permalink: concept-gcnv.html 
keywords: google cloud netapp volumes, cost, price, features, google cloud netapp volumes features, gcnv, supported regions, google regions, google cloud netapp volumes regions 
summary: Google Cloud NetApp Volumes consente alle aziende di migrare ed eseguire le loro applicazioni core business-critical ad alta intensità di prestazioni e sensibili alla latenza in Google senza dover effettuare il refactoring per il cloud. 
---
= Scopri di più su Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud NetApp Volumes è un servizio di storage dei dati basato sul cloud e completamente gestito, che offre capacità avanzate di gestione dei dati e performance altamente scalabili.

NetApp Volumes aiuta ad accelerare i tempi di distribuzione, gestire i carichi di lavoro e le applicazioni e migrare i carichi di lavoro sul cloud, mantenendo al contempo le prestazioni e le funzionalità dello storage locale.



== Caratteristiche

* Esegue le applicazioni aziendali in modo più rapido ed efficiente.
* Riduce i costi di archiviazione cloud fino al 90%.
* Rispetta i requisiti di uptime, disponibilità e sicurezza.
* Supporta ambienti NFS, SMB e multiprotocollo.




== Costo

I volumi creati da Google Cloud NetApp Volumes vengono addebitati sull'abbonamento al servizio, non tramite BlueXP.

Non sono previsti costi per scoprire una regione o un volume Google Cloud NetApp Volumes da BlueXP.



== Regioni supportate

https://cloud.google.com/netapp/volumes/docs/discover/service-levels#supported_regions["Visualizza le regioni supportate Google Cloud NetApp Volumes"^]



== Assistenza

Per supporto tecnico, invia una richiesta tramite il portale Google Cloud. Seleziona il tuo abbonamento Google Cloud e il servizio * Google Cloud NetApp Volumes* nella sezione *Storage*. Completa le informazioni richieste.

Utilizza la chat BlueXP per domande generali sul funzionamento Google Cloud NetApp Volumes in BlueXP.

Per domande generali su Google Cloud NetApp Volumes, inviare un'e-mail al team Google Cloud di NetApp all'indirizzo gcinfo@netapp.com.

Per problemi tecnici associati ai volumi cloud, puoi creare un caso di supporto tecnico da Google Cloud Console. Per ulteriori informazioni, vedere link:https://cloud.google.com/netapp/volumes/docs/support["ottenere supporto"^] .



== Link correlati

* https://cloud.google.com/netapp/volumes/docs/discover/overview["Documentazione Google Cloud NetApp Volumes"^]
* https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["Copia BlueXP e documentazione di sincronizzazione"^]

